context:
  name: pylance
  git_url: https://github.com/lancedb/lance.git
  git_tag: v2.0.0-rc.4
  version: ${{ git_tag[1:] | replace("-",".") }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - git: ${{ git_url }}
    tag: ${{ git_tag }}

build:
  python:
    version_independent: true
  script:
    - git restore .
    - cd python
    - pip install . -vv

requirements:
  build:
    - ${{ compiler("rust") }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - pkg-config
  host:
    - python
    - pip
    - maturin
    - grpcio
    - grpcio-tools
    - google-api-python-client
    - libprotobuf
  run:
    - python
    - numpy
    - pyarrow
    - lance-namespace
  ignore_run_exports:
    from_package:
      - libprotobuf

tests:
  - python:
      imports:
        - lance
