context:
  name: "liger-kernel"
  git_url: https://github.com/linkedin/Liger-Kernel.git
  git_tag: v0.6.2
  build_number: 0
  version: ${{ git_tag[1:] }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - git: ${{ git_url }}
    tag: ${{ git_tag }}
build:
  number: ${{ build_number }}
  noarch: python
  script:
    - pip install . -vv

requirements:
  host:
    - python
    - pip
    - packaging
    - setuptools
  run:
    - pytorch

tests:
  - python:
      imports:
        - liger_kernel
