name: "Setup pixi"
description: "Install pixi and add .pixi/envs/default/bin to PATH"
runs:
  using: "composite"
  steps:
    - name: Configure Git for private repos
      if: ${{ env.GITHUB_TOKEN != '' }}
      shell: bash
      run: |
        git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0.8.13
      with:
        pixi-version: v0.63.2
        pixi-url: https://github.com/fecet/pixi/releases/download/{{version}}/{{pixiFile}}
        run-install: true
        cache: true
    - name: Add .pixi/envs/default/bin to PATH
      shell: bash
      run: |
        echo "$(pwd)/.pixi/envs/default/bin" >> "$GITHUB_PATH"
    - name: Config pixi cache
      shell: bash
      run: |
        pixi config set --global repodata-config.disable-sharded true
        pixi config set --global repodata-config.disable-zstd true
