context:
  name: python-ninja
  git_url: https://github.com/scikit-build/ninja-python-distributions
  git_tag: 1.13.0
  build_number: 1
  # version: ${{ latest_tag }}

package:
  name: ${{ name }}
  version: ${{ git_tag }}

source:
  git: ${{ git_url }}
  tag: ${{ git_tag }}

build:
  script: pip install . -vv
  noarch: python
  number: ${{ build_number }}

requirements:
  build:
    - make
    - cmake
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - pip
    - scikit-build
    - scikit-build-core
    - setuptools-scm
    - hatch-fancy-pypi-readme
  run:
    - scikit-build
    - ninja

tests:
  - python:
      imports:
        - ninja
