context:
  name: certifi
  git_url: https://github.com/certifi/python-certifi.git
  git_tag: 2025.08.03

package:
  name: ${{ name|lower }}
  version: ${{ git_tag }}

source:
  git: ${{ git_url }}
  tag: ${{ git_tag }}

build:
  noarch: python
  script:
    - pip install . -vv --no-deps --no-build-isolation
    - cat $RECIPE_DIR/ca.crt >> $SP_DIR/certifi/cacert.pem
    - cat $SP_DIR/certifi/cacert.pem | grep MIIDADCCAei

requirements:
  # note that there is no build section
  host:
    - python
    - setuptools
    - pip

tests:
  - python:
      imports:
        - certifi
