context:
  name: "buildah"
  git_url: https://github.com/containers/buildah.git
  # git_tag: ${{ git.latest_tag( git_url ) }}
  git_tag: v1.41.0
  version: ${{ git_tag[1:] }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - git: ${{ git_url }}
    tag: ${{ git_tag }}
build:
  number: 0
  dynamic_linking:
    binary_relocation: false
  script:
    - patch -p1 < $RECIPE_DIR/01-relocate.patch
    # - sed -i.bak "s|var defaultHelperBinariesDir = \[\]string{|var defaultHelperBinariesDir = \[\]string{\n\t\"$PREFIX/lib/podman\",|" vendor/github.com/containers/common/pkg/config/config_linux.go
    # - |
    #   sed -i.bak 's|^\(// const char \*condaPrefix =\).*|\1 "'"${PREFIX}"'";|' \
    #   vendor/github.com/containers/common/pkg/config/config.go
    # - grep -qF "// const char *condaPrefix = \"${PREFIX}\";" vendor/github.com/containers/common/pkg/config/config.go || true
    - make PREFIX="${PREFIX}" bin/buildah docs
    - make PREFIX="${PREFIX}" install install.completions

requirements:
  build:
    - ${{ compiler('go-cgo') }}
    - ${{ compiler('c') }}
    - go-licenses
    - make
    - pkg-config
    - ${{ cdt('libselinux') }}
  host:
    - btrfs-progs
    - containers-common
    - gpgme
    - libdevmapper
    - libseccomp
  run:
    - conmon
    - cni-plugins
    - containers-common
    - runc
    - slirp4netns
    - netavark
    - gpgme
    - fuse-overlayfs
    - libsqlite
tests:
  - script:
      - ldd $PREFIX/bin/buildah
      - buildah --help
