context:
  git_url: https://github.com/sctp/lksctp-tools.git
  git_tag: v1.0.21
  name: ${{ git_url | split('/') | last | split('.') | first }}
  build_number: 1
  version: ${{ git_tag[1:] }}

recipe:
  name: ${{ name }}
  version: ${{ version }}

cache:
  source:
    - git: ${{ git_url }}
      tag: ${{ git_tag }}
  requirements:
    build:
      # - ${{ compiler('cxx') }}
      # - ${{ compiler('c') }}
      - ${{ stdlib("c") }}
      - autoconf
      - automake
      - libtool
      - make
  build:
    script:
      # - ln -sf $BUILD_PREFIX/bin/make $BUILD_PREFIX/bin/gmake
      - ./bootstrap
      - ./configure --prefix=$PREFIX
      - make -j $CPU_COUNT
      - make install

outputs:
  - package:
      name: lk${{ name }}-tools
    build:
      number: ${{ build_number }}
      files:
        include:
          - "bin/*"
          - "lib/lksctp-tools/**"
          - "lib/share/lksctp-tools/**"
  - package:
      name: lib${{ name }}
    build:
      number: ${{ build_number }}
      files:
        include:
          - "lib/lib${{ name }}*.so"
  - package:
      name: lib${{ name }}-dev
    requirements:
      run:
        - ${{ pin_subpackage('lib'+name, lower_bound="x.x.x", upper_bound="x.x.x") }}
      run_exports:
        - ${{ pin_subpackage('lib'+name, lower_bound="x.x.x", upper_bound="x.x.x") }}
    build:
      number: ${{ build_number }}
      files:
        include:
          - "lib/lib${{ name }}*.a"
          - "lib/lib${{ name }}*.la"
          - "lib/pkgconfig/*"
          - "include/*/**"
          - "share/man/*/**"
