context:
  name: "faster-whisper"
  git_url: https://github.com/SYSTRAN/faster-whisper.git
  git_tag: v1.2.0
  build_number: 0
  version: ${{ git_tag[1:] }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - git: ${{ git_url }}
    tag: ${{ git_tag }}

build:
  noarch: python
  number: ${{ build_number }}
  script:
    - pip install . -vv
  # python:
  #   entry_points:
  #     - aider = aider.main:main

requirements:
  host:
    - setuptools >=68
    - setuptools_scm >=8
    - python <3.13, >=3.9
    - pip
  run:
    - onnxruntime
    - av
    - ctranslate2
    - tokenizers
    - huggingface_hub
    - tqdm
tests:
  - script:
      interpreter: python
      content: |
        from faster_whisper import WhisperModel
