context:
  name: "qemu"
  git_tag: "v10.1.0-rc3"
  git_url: https://github.com/qemu/qemu
  build_number: 0

package:
  name: ${{ name }}
  version: ${{ git_tag[1:] | replace('-','.') }}

source:
  - git: ${{ git_url }}
    tag: ${{ git_tag }}
    patches:
      - 01-symbol.patch

build:
  number: ${{ build_number }}
  script:
    # - |
    #   export MAX_JOBS=$(($CPU_COUNT > 64 ? 64 : $CPU_COUNT ))
    - mkdir -p build && cd build
    - export CFLAGS="-I$SRC_DIR -I$SRC_DIR/include $CFLAGS"
    - |
      ../configure \
      --prefix="$PREFIX" \
      --target-list="x86_64-linux-user,x86_64-softmmu" \
      --enable-user \
      --enable-tools \
      --enable-qcow1 \
      --enable-virtfs \
      --enable-kvm \
      --enable-vhost-net \
      --enable-fuse \
      --enable-vte \
      --disable-werror

      # --python $BUILD_PREFIX/bin/python
      # --enable-tools \
      # || (cat $SRC_DIR/build/meson-logs/meson-log.txt && /usr/bin/false)
    - make -j $CPU_COUNT
    - make install

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - make
    - pkg-config
    - ninja
    - gettext
    - flex
    - bison
  host:
    - glib
    - gmp
    - libnuma
    - libfdt
    - libdrm
    - valgrind
    - libfuse
    - liburing

    - sphinx
    - sphinx-rtd-theme
  run:
    - libnuma
    - ncurses
    - virtiofsd

tests:
  - script:
      - set -ex
      - ldd $(which qemu-system-x86_64)
      - ldd $(which qemu-img)
      - qemu-img --help
      - qemu-system-x86_64 --help
      # - qemu-system-x86_64 --enable-kvm
